name: Deploy to NGINX Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Este paso es para asegurarnos de que el código esté disponible

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@149.50.142.112 << 'EOF'
          cd /var/www/html
          git pull origin main  # Aquí se hace el pull para actualizar el servidor con los cambios
          # Si necesitas reiniciar NGINX (por ejemplo, si actualizas archivos de configuración):
          sudo systemctl restart nginx
        EOF
